package docker

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"OpsVault/internal/driver"
	"OpsVault/pkg/credutil"
	"OpsVault/pkg/logger"

	"github.com/docker/docker/api/types/container"
	"github.com/docker/go-connections/nat"
	"github.com/spf13/viper"
)

type GitLabDriver struct {
	*BaseDriver
}

func NewGitLabDriver(cli DockerClient, cfg *viper.Viper) *GitLabDriver {
	port := cfg.GetInt("gitlab.port")
	if port == 0 {
		port = 8082
	}
	sshPort := cfg.GetInt("gitlab.ssh_port")
	if sshPort == 0 {
		sshPort = 2222
	}
	httpsPort := cfg.GetInt("gitlab.https_port")
	if httpsPort == 0 {
		httpsPort = 8443
	}
	image := cfg.GetString("gitlab.image")
	if image == "" {
		image = "gitlab/gitlab-ce:latest"
	}
	base := NewBaseDriver("gitlab", cli.Raw(), cfg, image, []string{
		fmt.Sprintf("%d:80", port),
		fmt.Sprintf("%d:22", sshPort),
		fmt.Sprintf("%d:443", httpsPort),
	})
	drv := &GitLabDriver{BaseDriver: base}
	drv.PrepareConfig = drv.prepareConfig
	return drv
}

func (d *GitLabDriver) Install() error {
	return d.installWithSpec(d.containerSpec)
}

func (d *GitLabDriver) containerSpec() (*container.Config, *container.HostConfig, error) {
	port := nat.Port("80/tcp")
	sshPort := nat.Port("22/tcp")
	httpsPort := nat.Port("443/tcp")

	hostPort := d.Config.GetString("gitlab.port")
	if hostPort == "" {
		hostPort = "8082"
	}
	hostSSHPort := d.Config.GetString("gitlab.ssh_port")
	if hostSSHPort == "" {
		hostSSHPort = "2222"
	}
	hostHTTPSPort := d.Config.GetString("gitlab.https_port")
	if hostHTTPSPort == "" {
		hostHTTPSPort = "8443"
	}

	return &container.Config{
			Image: d.Image,
			Healthcheck: &container.HealthConfig{
				Test:        []string{"CMD-SHELL", "gitlab-ctl status || exit 1"},
				Interval:    30 * time.Second,
				Timeout:     10 * time.Second,
				StartPeriod: 120 * time.Second,
				Retries:     10,
			},
		}, &container.HostConfig{
			Binds: []string{
				toDockerBind(filepath.Join(d.DataDir, "config"), "/etc/gitlab"),
				toDockerBind(filepath.Join(d.DataDir, "logs"), "/var/log/gitlab"),
				toDockerBind(filepath.Join(d.DataDir, "data"), "/var/opt/gitlab"),
			},
			PortBindings: nat.PortMap{
				port:      []nat.PortBinding{{HostIP: d.BindIP, HostPort: hostPort}},
				sshPort:   []nat.PortBinding{{HostIP: d.BindIP, HostPort: hostSSHPort}},
				httpsPort: []nat.PortBinding{{HostIP: d.BindIP, HostPort: hostHTTPSPort}},
			},
		}, nil
}

func (d *GitLabDriver) prepareConfig(confDir string) error {
	configDir := filepath.Join(d.DataDir, "config")
	logsDir := filepath.Join(d.DataDir, "logs")
	dataDir := filepath.Join(d.DataDir, "data")

	if err := os.MkdirAll(configDir, 0o755); err != nil {
		return err
	}
	if err := os.MkdirAll(logsDir, 0o755); err != nil {
		return err
	}
	if err := os.MkdirAll(dataDir, 0o755); err != nil {
		return err
	}

	rbFile := filepath.Join(configDir, "gitlab.rb")
	port := d.Config.GetInt("gitlab.port")
	if port == 0 {
		port = 8082
	}
	sshPort := d.Config.GetInt("gitlab.ssh_port")
	if sshPort == 0 {
		sshPort = 2222
	}
	extURL := d.Config.GetString("gitlab.external_url")
	if extURL == "" {
		extURL = fmt.Sprintf("http://localhost:%d", port)
	}
	pumaWorkers := d.Config.GetInt("gitlab.puma_workers")
	if pumaWorkers <= 0 {
		pumaWorkers = 2
	}

	if _, err := os.Stat(rbFile); os.IsNotExist(err) {
		content := fmt.Sprintf(`# Auto-generated by OpsVault to prevent port & memory issues
external_url '%s'
nginx['listen_port'] = 80
puma['worker_processes'] = %d
puma['per_worker_max_memory_mb'] = 1024
gitlab_rails['gitlab_shell_ssh_port'] = %d
`, extURL, pumaWorkers, sshPort)
		if err := os.WriteFile(rbFile, []byte(content), 0o644); err != nil {
			return fmt.Errorf("failed to write gitlab.rb: %w", err)
		}
	} else {
		data, err := os.ReadFile(rbFile)
		if err == nil {
			contentStr := string(data)
			lines := strings.Split(contentStr, "\n")
			hasSSHPort := false
			hasPuma := false
			hasNginx := false

			targetSSHLine := fmt.Sprintf("gitlab_rails['gitlab_shell_ssh_port'] = %d", sshPort)
			targetPumaLine := fmt.Sprintf("puma['worker_processes'] = %d", pumaWorkers)

			for i, line := range lines {
				trimmed := strings.TrimSpace(line)
				if strings.Contains(trimmed, "gitlab_shell_ssh_port") {
					if !strings.HasPrefix(trimmed, "#") {
						lines[i] = targetSSHLine
						hasSSHPort = true
					}
				}
				if strings.Contains(trimmed, "puma['worker_processes']") {
					if !strings.HasPrefix(trimmed, "#") {
						lines[i] = targetPumaLine
						hasPuma = true
					}
				}
				if strings.Contains(trimmed, "nginx['listen_port']") {
					if !strings.HasPrefix(trimmed, "#") {
						hasNginx = true
					}
				}
			}

			var toAppend []string
			if !hasSSHPort {
				toAppend = append(toAppend, targetSSHLine)
			}
			if !hasPuma {
				toAppend = append(toAppend, targetPumaLine)
			}
			if !hasNginx {
				toAppend = append(toAppend, "nginx['listen_port'] = 80")
			}

			newContent := strings.Join(lines, "\n")
			if len(toAppend) > 0 {
				if !strings.HasSuffix(newContent, "\n") {
					newContent += "\n"
				}
				newContent += "# Appended by OpsVault optimization\n" + strings.Join(toAppend, "\n") + "\n"
			}
			if newContent != contentStr {
				_ = os.WriteFile(rbFile, []byte(newContent), 0o644)
			}
		}
	}

	return nil
}

func (d *GitLabDriver) Restart() error {
	logger.Infof("[%s] Restarting Docker container %s...", d.Name, d.ContainerName)
	if err := d.checkAndInstallDocker(); err != nil {
		return err
	}
	if d.Client == nil {
		return fmt.Errorf("docker client is not available")
	}

	ctx := context.Background()
	if err := d.EnsureReady(ctx); err != nil {
		logger.Errorf("[%s] Failed EnsureReady during restart: %v", d.Name, err)
		return err
	}

	inspect, err := d.Client.ContainerInspect(ctx, d.ContainerName)
	if err == nil && inspect.HostConfig != nil {
		hostPort := d.Config.GetString("gitlab.port")
		if hostPort == "" {
			hostPort = "8082"
		}
		hostSSHPort := d.Config.GetString("gitlab.ssh_port")
		if hostSSHPort == "" {
			hostSSHPort = "2222"
		}
		hostHTTPSPort := d.Config.GetString("gitlab.https_port")
		if hostHTTPSPort == "" {
			hostHTTPSPort = "8443"
		}

		targetPorts := map[nat.Port]string{
			nat.Port("80/tcp"):  hostPort,
			nat.Port("22/tcp"):  hostSSHPort,
			nat.Port("443/tcp"): hostHTTPSPort,
		}

		if portsNeedUpdate(inspect.HostConfig.PortBindings, targetPorts) {
			logger.Infof("[%s] Port mapping changed, recreating container %s...", d.Name, d.ContainerName)
			timeout := 10
			_ = d.Client.ContainerStop(ctx, d.ContainerName, container.StopOptions{Timeout: &timeout})
			if err := d.Client.ContainerRemove(ctx, d.ContainerName, container.RemoveOptions{Force: true}); err != nil {
				logger.Errorf("[%s] Failed to remove container for recreation: %v", d.Name, err)
				return err
			}
			return d.installWithSpec(d.containerSpec)
		}
	}

	if err := d.Stop(); err != nil {
		return err
	}
	return d.Start()
}

func portsNeedUpdate(actual nat.PortMap, target map[nat.Port]string) bool {
	if actual == nil {
		return true
	}
	for containerPort, expectedHostPort := range target {
		bindings, ok := actual[containerPort]
		if !ok || len(bindings) == 0 {
			return true
		}
		if bindings[0].HostPort != expectedHostPort {
			return true
		}
	}
	return false
}

func (d *GitLabDriver) Upgrade(targetVersion string) error {
	return d.recreateWithImage(targetVersion, d.containerSpec)
}

func (d *GitLabDriver) GetCredentials() []credutil.Credential {
	port := d.Config.GetString("gitlab.port")
	if port == "" {
		port = "8082"
	}
	creds := []credutil.Credential{
		{Label: "访问地址", Value: fmt.Sprintf("http://localhost:%s", port)},
		{Label: "默认用户", Value: "root"},
	}

	pwdFile := filepath.Join(d.DataDir, "config", "initial_root_password")
	if data, err := os.ReadFile(pwdFile); err == nil {
		lines := strings.Split(string(data), "\n")
		pwd := ""
		for _, line := range lines {
			if strings.HasPrefix(line, "Password:") {
				pwd = strings.TrimSpace(strings.TrimPrefix(line, "Password:"))
				break
			}
		}
		if pwd != "" {
			creds = append(creds, credutil.Credential{Label: "初始密码", Value: pwd})
		}
	} else {
		creds = append(creds, credutil.Credential{
			Label: "初始密码",
			Value: fmt.Sprintf("可在宿主机运行此命令查看:\ncat %s", pwdFile),
		})
	}
	return creds
}

// Make sure GitLabDriver implements ServiceDriver and CredentialProvider
var _ driver.ServiceDriver = (*GitLabDriver)(nil)
var _ driver.CredentialProvider = (*GitLabDriver)(nil)
