ansible:
    inventory:
        groups:
            - name: "db_servers"
              hosts:
                - ip: "127.0.0.1"
                  port: 22
                  user: "root"
                  ssh_private_key: "/root/.ssh/id_rsa"
            - name: "web_servers"
              hosts:
                - ip: "127.0.0.1"
                  port: 22
                  user: "root"
                  ssh_private_key: "/root/.ssh/id_rsa"
