docker:
    cidr: 172.28.0.0/16
    data_root: /data/opsvault
    network_name: opsvault-net
    resource_limit:
        cpu_max: "2"
        mem_max: 2g
backup:
    storage_path: /data/opsvault/bak
log:
    level: info
    storage_path: /data/opsvault/logs
mode: docker
mysql:
    image: mysql:8.0
    port: 3306
    root_password: "123456"
nginx:
    install_path: /usr/local/nginx
    logrotate_path: /etc/logrotate.d/nginx
    openssl_version: 1.1.1w
    pcre_version: "8.45"
    run_group: www
    run_user: www
    source_root: /usr/local/src/opsvault-nginx
    ssl_root: /data/ssl
    systemd_unit_path: /lib/systemd/system/nginx.service
    version: 1.31.0
    www_root: /data/wwwroot
    wwwlogs_root: /data/wwwlogs
postgres:
    image: postgres:15
    password: "123456"
    port: 5432
rabbitmq:
    admin_pwd: password
    admin_user: admin
    image: rabbitmq:3-management
    port: 5672
    ui_port: 15672
redis:
    image: redis:7-alpine
    password: "123456"
    port: 6379
rocketmq:
    broker_port: 10911
    image: apache/rocketmq:5.3.0
    namesrv_port: 9876
